# Generated by Django 4.1.9 on 2023-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_profile_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roll_num',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
